# Generated by Django 2.0.5 on 2020-04-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='email@email.org', max_length=254),
            preserve_default=False,
        ),
    ]
